@startuml
skinparam defaultFontSize 16
!define InterfaceMD circle #green
!define ClassMD circle #black
!define ExternalMD circle #red
ExternalMD {
FontSize 30
BackGroundColor yellow
Margin 30
Padding 50
}
ClassMD DocumentStructure
ClassMD PageSize
ClassMD PageSnapshotIndex
ClassMD RenderedPageSnapshot
ClassMD InteractiveCanvas
ClassMD PreviewerWindow
ClassMD PreviewerControl
ClassMD PreviewerWindowViewModel
ClassMD PreviewerApp
ClassMD CommunicationService
ClassMD Settings
ClassMD ReportModel
ClassMD ReportHeaderField
ClassMD Location
ClassMD ReportSection
ClassMD ReportSectionElement
ClassMD ReportSectionText
ClassMD ReportSectionMap
ClassMD ReportSectionPhotos
ClassMD ReportPhoto
ClassMD DataSource
ClassMD Helpers
ClassMD Typography
ClassMD LicenseSetup
ClassMD SkiaSharpHelpers
ClassMD Colors
ClassMD Red
ClassMD Pink
ClassMD Purple
ClassMD DeepPurple
ClassMD Indigo
ClassMD Blue
ClassMD LightBlue
ClassMD Cyan
ClassMD Teal
ClassMD Green
ClassMD LightGreen
ClassMD Lime
ClassMD Yellow
ClassMD Amber
ClassMD Orange
ClassMD DeepOrange
ClassMD Brown
ClassMD Grey
ClassMD BlueGrey
ClassMD Fonts
ClassMD Placeholders
ClassMD NativeDependencyCompatibilityChecker
ClassMD PageSizes
ClassMD PageSizeExtensions
ClassMD ColorParser
ClassMD ExceptionDocument
ClassMD Extensions
ClassMD HotReloadManager
ClassMD PreviewerService
ClassMD Empty
ClassMD ShowEntire
ClassMD Image
ClassMD Border
ClassMD Padding
ClassMD Layer
ClassMD Layers
ClassMD Container
ClassMD RowItem
ClassMD RowItemRenderingCommand
ClassMD Row
ClassMD Extend
ClassMD SectionLink
ClassMD SkipOnce
ClassMD Inlined
ClassMD Placeholder
ClassMD DebugArea
ClassMD DynamicHost
ClassMD DynamicContext
ClassMD DynamicElement
ClassMD Unconstrained
ClassMD Section
ClassMD DefaultTextStyle
ClassMD LayoutOverflowVisualization
ClassMD Alignment
ClassMD ColumnItemRenderingCommand
ClassMD Column
ClassMD Hyperlink
ClassMD RepeatContent
ClassMD Rotate
ClassMD SimpleRotate
ClassMD GridElement
ClassMD Grid
ClassMD Line
ClassMD EnsureSpace
ClassMD SvgPath
ClassMD DecorationItemRenderingCommand
ClassMD Decoration
ClassMD Shrink
ClassMD ScaleToFit
ClassMD SvgImage
ClassMD Constrained
ClassMD AspectRatio
ClassMD DebugPointer
ClassMD Page
ClassMD PageBreak
ClassMD Translate
ClassMD ShowOnce
ClassMD Background
ClassMD ShowIfContext
ClassMD ShowIf
ClassMD DynamicSvgImage
ClassMD Scale
ClassMD GenerateDynamicImageDelegatePayload
ClassMD DynamicImage
ClassMD ContentDirectionSetter
ClassMD StopPaging
ClassMD Slot
ClassMD DocumentMetadata
ClassMD TextStyleManager
ClassMD DocumentSettings
ClassMD PageContext
ClassMD DocumentLocation
ClassMD MergedDocument
ClassMD ImageGenerationSettings
ClassMD UnitExtensions
ClassMD ContainerElement
ClassMD Element
ClassMD DynamicComponentProxy
ClassMD DynamicComponentComposeResult
ClassMD Utf8StringMarshaller
ClassMD SkPictureRecorder
ClassMD API
ClassMD SkDocument
ClassMD SkiaAPI
ClassMD SkPdfDocument
ClassMD SkNativeDependencyProvider
ClassMD SkBitmap
ClassMD SkWriteStream
ClassMD SkSvgCanvas
ClassMD SkNativeDependencyCompatibilityChecker
ClassMD SkCanvas
ClassMD SkImage
ClassMD SkXpsDocument
ClassMD SkSvgImage
ClassMD SkData
ClassMD SkText
ClassMD SkPicture
ClassMD FreeCanvas
ClassMD PreviewerPageSnapshot
ClassMD PreviewerDocumentSnapshot
ClassMD PreviewerCanvas
ClassMD SkiaDocumentCanvasBase
ClassMD DocumentGenerator
ClassMD SkiaCanvasBase
ClassMD DocumentContainer
ClassMD FontManager
ClassMD SvgCanvas
ClassMD ImageCanvas
ClassMD PdfCanvas
ClassMD XpsCanvas
ClassMD PaddingExtensions
ClassMD GenerateExtensions
ClassMD RotateExtensions
ClassMD DynamicImageDescriptor
ClassMD ImageDescriptor
ClassMD ImageExtensions
ClassMD ScaleExtensions
ClassMD GridDescriptor
ClassMD GridExtensions
ClassMD DebugExtensions
ClassMD ContentDirectionExtensions
ClassMD InlinedDescriptor
ClassMD InlinedExtensions
ClassMD TranslateExtensions
ClassMD LayersDescriptor
ClassMD LayerExtensions
ClassMD BorderExtensions
ClassMD TextStyleExtensions
ClassMD AlignmentExtensions
ClassMD ComponentDescriptor
ClassMD ComponentExtensions
ClassMD LineExtensions
ClassMD DecorationDescriptor
ClassMD DecorationExtensions
ClassMD SvgImageDescriptor
ClassMD SvgExtensions
ClassMD ShrinkExtensions
ClassMD PageDescriptor
ClassMD PageExtensions
ClassMD DynamicComponentExtensions
ClassMD ColumnDescriptor
ClassMD ColumnExtensions
ClassMD TextSpanDescriptor
ClassMD TextPageNumberDescriptor
ClassMD TextBlockDescriptor
ClassMD TextDescriptor
ClassMD TextExtensions
ClassMD ElementExtensions
ClassMD Document
ClassMD TableColumnsDefinitionDescriptor
ClassMD TableCellDescriptor
ClassMD TableDescriptor
ClassMD TableExtensions
ClassMD TableCellExtensions
ClassMD ConstrainedExtensions
ClassMD ExtendExtensions
ClassMD RowDescriptor
ClassMD RowExtensions
ClassMD TextSpanDescriptorExtensions
ClassMD PhotoTemplate
ClassMD ImagePlaceholder
ClassMD DifferentHeadersTemplate
ClassMD StandardReport
ClassMD SectionTemplate
ClassMD TableOfContentsTemplate
ClassMD RenderingTest
ClassMD SimpleDocument
ClassMD TableLayoutPlanner
ClassMD TableColumnDefinition
ClassMD TableLayoutValidator
ClassMD TableCell
ClassMD TableCellRenderingCommand
ClassMD DynamicDictionary
ClassMD Table
ClassMD TextBlock
ClassMD SkParagraphBuilderPoolManager
ClassMD SkTextStyle
ClassMD SkFontCollection
ClassMD SkFontManager
ClassMD SkParagraph
ClassMD SkTypefaceProvider
ClassMD SkTypeface
ClassMD SkParagraphBuilder
ClassMD TreeNode
ClassMD TreeTraversal
ClassMD ElementProxy
ClassMD OverflowDebuggingProxy
ClassMD CacheProxy
ClassMD InitializationException
ClassMD DocumentComposeException
ClassMD DocumentDrawingException
ClassMD DocumentLayoutException
ClassMD TextBlockSpan
ClassMD TextBlockPageNumber
ClassMD TextBlockElement
ClassMD TextBlockHyperlink
ClassMD TextBlockSectionLink
ClassMD TextBlockParagraphSpacing
InterfaceMD IDynamicElement
InterfaceMD ILine
InterfaceMD IContainer
InterfaceMD ISlot
InterfaceMD IComponent
InterfaceMD IRenderingCanvas
InterfaceMD IContentDirectionAware
InterfaceMD ICanvas
InterfaceMD IStateResettable
InterfaceMD IDocumentContainer
InterfaceMD IPageContext
InterfaceMD ICacheable
InterfaceMD IDocument
InterfaceMD IDynamicComponent
InterfaceMD IElement
InterfaceMD ITableCellContainer
InterfaceMD ITextBlockItem
ExternalMD ICustomDrawOperation
ExternalMD Window
ExternalMD Control
ExternalMD ReactiveObject
ExternalMD Application
ExternalMD ICustomMarshaler
ExternalMD IDisposable
ExternalMD Exception
RenderedPageSnapshot  --> PageSnapshotIndex
ReportSectionText  --> ReportSectionElement
ReportSectionMap  --> ReportSectionElement
ReportSectionPhotos  --> ReportSectionElement
ExceptionDocument --> IDocument
Empty  --> Element
ShowEntire  --> ContainerElement
ShowEntire --> ICacheable
Image  --> Element
Image --> IStateResettable
Image --> ICacheable
Border  --> ContainerElement
Padding  --> ContainerElement
Padding --> ICacheable
Layer  --> ContainerElement
Layers  --> Element
Layers --> ICacheable
Container  --> ContainerElement
RowItem  --> Container
Row  --> Element
Row --> IContentDirectionAware
Row --> IStateResettable
Row --> ICacheable
Extend  --> ContainerElement
Extend --> ICacheable
SectionLink  --> ContainerElement
SkipOnce  --> ContainerElement
SkipOnce --> IStateResettable
Inlined  --> Element
Inlined --> IStateResettable
Inlined --> IContentDirectionAware
Placeholder --> IComponent
DebugArea --> IComponent
DynamicHost  --> Element
DynamicHost --> IContentDirectionAware
DynamicHost --> IStateResettable
DynamicElement  --> ContainerElement
DynamicElement --> IDynamicElement
Unconstrained  --> ContainerElement
Unconstrained --> ICacheable
Unconstrained --> IContentDirectionAware
Section  --> ContainerElement
Section --> IStateResettable
DefaultTextStyle  --> ContainerElement
LayoutOverflowVisualization  --> ContainerElement
LayoutOverflowVisualization --> IContentDirectionAware
Alignment  --> ContainerElement
Column  --> Element
Column --> IStateResettable
Column --> ICacheable
Hyperlink  --> ContainerElement
Hyperlink --> IContentDirectionAware
RepeatContent  --> ContainerElement
Rotate  --> ContainerElement
SimpleRotate  --> ContainerElement
SimpleRotate --> ICacheable
Grid --> IComponent
Line  --> Element
Line --> IStateResettable
Line --> ICacheable
Line --> ILine
EnsureSpace  --> ContainerElement
EnsureSpace --> ICacheable
SvgPath  --> Element
SvgPath --> IStateResettable
Decoration  --> Element
Decoration --> IContentDirectionAware
Decoration --> ICacheable
Shrink  --> ContainerElement
Shrink --> IContentDirectionAware
ScaleToFit  --> ContainerElement
SvgImage  --> Element
SvgImage --> IStateResettable
Constrained  --> ContainerElement
Constrained --> IContentDirectionAware
Constrained --> ICacheable
AspectRatio  --> ContainerElement
AspectRatio --> IContentDirectionAware
AspectRatio --> ICacheable
DebugPointer  --> Container
Page --> IComponent
PageBreak  --> Element
PageBreak --> IStateResettable
Translate  --> ContainerElement
ShowOnce  --> ContainerElement
ShowOnce --> ICacheable
ShowOnce --> IStateResettable
Background  --> ContainerElement
ShowIf  --> ContainerElement
DynamicSvgImage  --> Element
DynamicSvgImage --> IStateResettable
Scale  --> ContainerElement
Scale --> ICacheable
DynamicImage  --> Element
DynamicImage --> IStateResettable
ContentDirectionSetter  --> ContainerElement
StopPaging  --> ContainerElement
Slot  --> Container
Slot --> ISlot
PageContext --> IPageContext
MergedDocument --> IDocument
ContainerElement  --> Element
ContainerElement --> IContainer
Element --> IElement
FreeCanvas --> IRenderingCanvas
FreeCanvas --> ICanvas
PreviewerCanvas  --> SkiaCanvasBase
SkiaDocumentCanvasBase  --> SkiaCanvasBase
SkiaCanvasBase --> IRenderingCanvas
SkiaCanvasBase --> ICanvas
DocumentContainer --> IDocumentContainer
SvgCanvas  --> SkiaCanvasBase
ImageCanvas  --> SkiaCanvasBase
PdfCanvas  --> SkiaDocumentCanvasBase
XpsCanvas  --> SkiaDocumentCanvasBase
TextPageNumberDescriptor  --> TextSpanDescriptor
TextBlockDescriptor  --> TextSpanDescriptor
Document --> IDocument
PhotoTemplate --> IComponent
ImagePlaceholder --> IComponent
DifferentHeadersTemplate --> IDocument
StandardReport --> IDocument
SectionTemplate --> IComponent
TableOfContentsTemplate --> IComponent
SimpleDocument --> IDocument
TableCell  --> Container
TableCell --> ITableCellContainer
Table  --> Element
Table --> IContentDirectionAware
Table --> IStateResettable
TextBlock  --> Element
TextBlock --> IContentDirectionAware
TextBlock --> IStateResettable
ElementProxy  --> ContainerElement
OverflowDebuggingProxy  --> ElementProxy
CacheProxy  --> ElementProxy
TextBlockSpan --> ITextBlockItem
TextBlockPageNumber  --> TextBlockSpan
TextBlockElement --> ITextBlockItem
TextBlockHyperlink  --> TextBlockSpan
TextBlockSectionLink  --> TextBlockSpan
TextBlockParagraphSpacing --> ITextBlockItem
@enduml
