@startuml
skinparam defaultFontSize 16
!define InterfaceMD circle #green
!define ClassMD circle #black
!define ExternalMD circle #red
ExternalMD {
FontSize 30
BackGroundColor yellow
Margin 30
Padding 50
}
ClassMD ReportModel
ClassMD ReportHeaderField
ClassMD Location
ClassMD ReportSection
ClassMD ReportSectionElement
ClassMD ReportSectionText
ClassMD ReportSectionMap
ClassMD ReportSectionPhotos
ClassMD ReportPhoto
ClassMD PreviewerWindow
ClassMD PreviewerWindowViewModel
ClassMD DocumentStructure
ClassMD PageSize
ClassMD PageSnapshotIndex
ClassMD RenderedPageSnapshot
ClassMD DocumentLocation
ClassMD Slot
ClassMD DocumentSettings
ClassMD ImageGenerationSettings
ClassMD Fonts
ClassMD DebugPointer
ClassMD TableCell
ClassMD TableColumnDefinition
ClassMD TextBlockHyperlink
InterfaceMD ICacheable
InterfaceMD IPageContext
InterfaceMD IStateResettable
InterfaceMD IDocumentContainer
InterfaceMD IElement
InterfaceMD ICanvas
InterfaceMD ISlot
InterfaceMD IComponent
InterfaceMD IDocument
InterfaceMD IContainer
InterfaceMD IRenderingCanvas
InterfaceMD IContentDirectionAware
InterfaceMD ITextBlockItem
ExternalMD Window
ExternalMD ReactiveObject
ExternalMD Container
ExternalMD ITableCellContainer
ExternalMD TextBlockSpan
ReportSectionText  --> ReportSectionElement
ReportSectionMap  --> ReportSectionElement
ReportSectionPhotos  --> ReportSectionElement
RenderedPageSnapshot  --> PageSnapshotIndex
Slot --> ISlot
@enduml
