@startuml
left to right direction
skinparam defaultFontSize 16
!define InternalMD circle #green
!define ExternalMD circle #red
ExternalMD {
FontSize 30
BackGroundColor yellow
Margin 30
Padding 50
}
InternalMD QuestPDF
ExternalMD SkiaSharp
ExternalMD System.Collections.Concurrent
ExternalMD Avalonia
ExternalMD Avalonia.Media
ExternalMD Avalonia.Platform
ExternalMD Avalonia.Rendering.SceneGraph
ExternalMD Avalonia.Skia
ExternalMD Avalonia.Controls
ExternalMD Avalonia.Controls.Primitives
ExternalMD Avalonia.Markup.Xaml
ExternalMD System.Collections.ObjectModel
ExternalMD System.Text.Json
ExternalMD Microsoft.AspNetCore.Builder
ExternalMD Microsoft.AspNetCore.Hosting
ExternalMD Microsoft.AspNetCore.Http
ExternalMD Microsoft.Extensions.DependencyInjection
ExternalMD Microsoft.Extensions.Logging
ExternalMD System
ExternalMD QuestPDF.Fluent
ExternalMD NUnit.Framework
ExternalMD System.Collections.Generic
ExternalMD System.Linq
ExternalMD QuestPDF.Skia.Text
ExternalMD System.Runtime.InteropServices
ExternalMD QuestPDF.Drawing.Exceptions
InternalMD QuestPDF.Previewer
InternalMD QuestPDF.Helpers
InternalMD QuestPDF.Elements
InternalMD QuestPDF.Infrastructure
InternalMD QuestPDF.Skia
InternalMD QuestPDF.Drawing
InternalMD QuestPDF.Elements.Table
InternalMD QuestPDF.Elements.Text
InternalMD QuestPDF.Elements.Text.Items
QuestPDF  --> SkiaSharp
QuestPDF  --> System.Collections.Concurrent
QuestPDF  --> Avalonia
QuestPDF  --> Avalonia.Media
QuestPDF  --> Avalonia.Platform
QuestPDF  --> Avalonia.Rendering.SceneGraph
QuestPDF  --> Avalonia.Skia
QuestPDF  --> Avalonia.Controls
QuestPDF  --> Avalonia.Controls.Primitives
QuestPDF  --> Avalonia.Markup.Xaml
QuestPDF  --> System.Collections.ObjectModel
QuestPDF  --> System.Text.Json
QuestPDF  --> Microsoft.AspNetCore.Builder
QuestPDF  --> Microsoft.AspNetCore.Hosting
QuestPDF  --> Microsoft.AspNetCore.Http
QuestPDF  --> Microsoft.Extensions.DependencyInjection
QuestPDF  --> Microsoft.Extensions.Logging
QuestPDF  --> System
QuestPDF  --> QuestPDF.Helpers
QuestPDF  --> QuestPDF.Infrastructure
QuestPDF  --> QuestPDF.Fluent
QuestPDF  --> NUnit.Framework
QuestPDF  --> QuestPDF.Drawing
QuestPDF  --> System.Collections.Generic
QuestPDF  --> System.Linq
QuestPDF  --> QuestPDF.Elements
QuestPDF  --> QuestPDF.Skia
QuestPDF  --> QuestPDF.Skia.Text
QuestPDF  --> System.Runtime.InteropServices
QuestPDF  --> QuestPDF.Drawing.Exceptions
QuestPDF.Previewer  --> SkiaSharp
QuestPDF.Previewer  --> System.Collections.Concurrent
QuestPDF.Previewer  --> Avalonia
QuestPDF.Previewer  --> Avalonia.Media
QuestPDF.Previewer  --> Avalonia.Platform
QuestPDF.Previewer  --> Avalonia.Rendering.SceneGraph
QuestPDF.Previewer  --> Avalonia.Skia
QuestPDF.Previewer  --> Avalonia.Controls
QuestPDF.Previewer  --> Avalonia.Controls.Primitives
QuestPDF.Previewer  --> Avalonia.Markup.Xaml
QuestPDF.Previewer  --> System.Collections.ObjectModel
QuestPDF.Previewer  --> System.Text.Json
QuestPDF.Previewer  --> Microsoft.AspNetCore.Builder
QuestPDF.Previewer  --> Microsoft.AspNetCore.Hosting
QuestPDF.Previewer  --> Microsoft.AspNetCore.Http
QuestPDF.Previewer  --> Microsoft.Extensions.DependencyInjection
QuestPDF.Previewer  --> Microsoft.Extensions.Logging
QuestPDF.Previewer  --> System
QuestPDF.Previewer  --> QuestPDF.Helpers
QuestPDF.Previewer  --> QuestPDF.Infrastructure
QuestPDF.Previewer  --> QuestPDF.Fluent
QuestPDF.Previewer  --> NUnit.Framework
QuestPDF.Previewer  --> QuestPDF.Drawing
QuestPDF.Previewer  --> System.Collections.Generic
QuestPDF.Previewer  --> System.Linq
QuestPDF.Previewer  --> QuestPDF.Elements
QuestPDF.Previewer  --> QuestPDF.Skia
QuestPDF.Previewer  --> QuestPDF.Skia.Text
QuestPDF.Previewer  --> System.Runtime.InteropServices
QuestPDF.Previewer  --> QuestPDF.Drawing.Exceptions
QuestPDF.Infrastructure  --> QuestPDF.Elements
QuestPDF.Infrastructure  --> QuestPDF.Skia
QuestPDF.Infrastructure  --> QuestPDF.Skia.Text
QuestPDF.Skia  --> System.Runtime.InteropServices
@enduml
